apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-nextcloud 
  annotations:
    volume.beta.kubernetes.io/storage-class: nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 953Gi
