apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-data
spec:
  storageClassName: nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.240.0.35
    path: "/tank/data/nextcloud"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Mi
