apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-secret
spec:
  secretName: tls-secret
  dnsNames:
  - thedoodleproject.org 
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - thedoodleproject.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
