apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: mysql
  namespace: mysql
spec:
  version: "8.0-v1"
  storageType: Durable
  storage:
    existingClaim: "data-mysql"
    resources:
      requests:
        storage: 50Mi
  terminationPolicy: WipeOut
